### ISSUE TITLE
Document SEO tips

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/docs#11]
Things like

 - Adding topics
 - Adding the r-universe URL to the package description 
 - Getting GitHub stars

**Comment by maelle** [comment]
related planned/current content in the dev guide

https://github.com/ropensci/dev_guide/pull/752

https://github.com/ropensci/dev_guide/issues/780

**Comment by maelle** [comment]
"Getting GitHub stars" lol does one buy them (I'll link to https://ropensci.org/blog/2024/03/07/package-marketing/!)

**Comment by jeroen** [comment]
Just re-assigning this to myself to add some more tips.

**Comment by maelle** [comment]
Friendly reminder :smile_cat:
