### ISSUE TITLE
Update score metric

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/docs#29]
List all the things taken account into the package score: https://github.com/r-universe-org/cranlike-server/blob/master/routes/packages.js#L273-L300

Maybe also mention we can browse scores and metrics for all packages here: https://r-universe.dev/packages

**Comment by maelle** [comment]
I also wonder how we'll keep the source and docs in sync. Or could we write "at the time of writing" and point to the file where the score calculation will always be (hopefully)?

**Comment by jeroen** [comment]
Maybe for now we phrase it a little more generally and just name the most important factors of the score, without claiming to be exhaustive or referencing code.
