### ISSUE TITLE
Outline supported apis

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/docs#5]
Document:

   - https://jeroen.r-universe.dev/api/ls
   - https://jeroen.r-universe.dev/api/packages
   - https://jeroen.r-universe.dev/api/packages/V8
   - https://jeroen.r-universe.dev/api/search
   - https://r-universe.dev/api/search
   
For the `/api/packages` API document the `fields` and `all` parameters.
For `/api/search` API document the `q=` parameter with all fields.

Explain that searching globally with https://r-universe.dev/api/search only returns "indexed" packages.

Include examples how to use in R with jsonlite or on the command line with `jq`.

**Comment by maelle** [comment]
Maybe this could be a new page under the Browse section.

**Comment by maelle** [comment]
even if it's not browsing, it is about consuming content.

**Comment by maelle** [comment]
@jeroen friendly reminder about @noamross' question above, would this work? I'd gladly help/learn to help

**Comment by jeroen** [comment]
I haven't used swagger/openai but I suspect it is overkill. We have only one or two apis (depending on what you count), and only support GET so I don't think we need to introduce a framework to document this. But perhaps I am wrong and there is some value to making this formal.

**Comment by maelle** [comment]
If I were to start documenting the API next week, where would I find the existing parameters? :innocent:

**Comment by maelle** [comment]
I see your first comment lists some parameters but isn't there also some pagination?

**Comment by jeroen** [comment]
There is no pagination, only a `limit` for `/api/packages`. Some examples can be found in the apis tab, e.g. https://ropensci.r-universe.dev/apis

**Comment by maelle** [comment]
but search only returns 100 packages

**Comment by jeroen** [comment]
I think you can set a `limit` parameter: https://github.com/r-universe-org/cranlike-server/blob/master/routes/search.js
