### ISSUE TITLE
add more about sys reqs

### ISSUE THREAD

**Issue by maelle** [r-universe-org/docs#68]
> We also use check with pak for sysdeps, so I think it does if I understand the question: https://github.com/r-universe-org/build-source/blob/5830b8aa92d5524b3af6d1b617e605d1a2558543/R/buildtools.R#L315 

> But in addition we start with a build image that has most libraries preinstalled, so most things are already there: https://github.com/r-universe-org/base-image/blob/master/Dockerfile

by @jeroen

**Comment by jeroen** [comment]
This is pretty much what we have at https://docs.r-universe.dev/publish/debug-build.html#how-to-request-additional-third-party-system-requirements. So let's ask what part of that was unclear

**Comment by llrs** [comment]
I think I am mixing/confusing section 13.2 and section 5.3.2. Perhaps a link on both sections could be added?
